[package]
name = "launch-telemetry-app"
version = "0.1.0"
description = "Read-only rocket launch telemetry UI"
authors = ["MARV"]
edition = "2021"

[lib]
name = "launch_telemetry_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[workspace]
